import {
  Brain,
  Code,
  Code2,
  Database,
  FolderOpen,
  Globe,
  Layers,
  Link,
  Mail,
  Phone,
  Send,
  Server,
  Share2,
  Smartphone,
  Sparkles,
  Terminal,
  TestTube,
  User,
  Wrench,
  Zap,
} from "lucide-react";
import {
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiSass,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiPostgresql,
  SiRedis,
  SiExpo,
  SiFlutter,
  SiElectron,
  SiJest,
  SiDocker,
  SiKubernetes,
  SiGit,
  SiGithub,
  SiPostman,
  SiTensorflow,
  SiPytorch,
  SiOpenai,
  SiAstro,
  SiPwa,
  SiShadcnui,
  SiReactrouter,
  SiAxios,
} from "react-icons/si";

import {
  FaUserGraduate,
  FaGlobe,
  FaLanguage,
  FaRocket,
  FaLaptopCode,
  FaAws,
  FaDatabase,
  FaCode,
  FaServer,
  FaCss3Alt,
  FaReact,
  FaHtml5,
} from "react-icons/fa";

import { BsFillGearFill } from "react-icons/bs";
import { DiMongodb } from "react-icons/di";
import { IoLogoJavascript } from "react-icons/io";
import { TbBrandReactNative, TbBrandVite } from "react-icons/tb";
import { LuTreePalm } from "react-icons/lu";
import { VscRobot } from "react-icons/vsc";

const navLinks = [
  {
    id: 1,
    name: "Projects",
    type: "finder",
  },
  {
    id: 3,
    name: "Contact US",
    type: "contact",
  },
  {
    id: 4,
    name: "Resume",
    type: "resume",
  },
];

const dockApps = [
  {
    id: "finder",
    name: "Portfolio",
    icon: "finder.png",
    canOpen: true,
  },
  {
    id: "safari",
    name: "Courses",
    icon: "safari.png",
    canOpen: true,
  },
  {
    id: "photos",
    name: "Gallery",
    icon: "photos.png",
    canOpen: true,
  },
  {
    id: "contact",
    name: "Contact US",
    icon: "contact.png",
    canOpen: true,
  },
  {
    id: "terminal",
    name: "Skills",
    icon: "terminal.png",
    canOpen: true,
  },
  {
    id: "trash",
    name: "Archive",
    icon: "trash.png",
    canOpen: false,
  },
];

const layers = [
  {
    id: "frontend",
    title: "Frontend",
    description: "UI & Interaction",
    icon: Code2,
    categories: ["Frontend Core", "Styling & UI"],
    color: "from-blue-500 to-cyan-400",
  },
  {
    id: "state",
    title: "State & Data",
    description: "State Management & Data Fetching",
    icon: Sparkles,
    categories: ["State & Data"],
    color: "from-purple-500 to-pink-400",
  },
  {
    id: "backend",
    title: "Backend",
    description: "Server-Side Development",
    icon: Server,
    categories: ["Backend"],
    color: "from-green-500 to-emerald-400",
  },
  {
    id: "database",
    title: "Database",
    description: "Data Storage & Caching",
    icon: Database,
    categories: ["Database"],
    color: "from-amber-500 to-orange-400",
  },
  {
    id: "mobile",
    title: "Mobile & Desktop",
    description: "Cross-Platform Apps",
    icon: Smartphone,
    categories: ["Mobile & Desktop"],
    color: "from-indigo-500 to-blue-400",
  },
  {
    id: "architecture",
    title: "Architecture",
    description: "PWA & API Design",
    icon: Layers,
    categories: ["Architecture & PWA"],
    color: "from-rose-500 to-red-400",
  },
  {
    id: "testing",
    title: "Testing",
    description: "Quality Assurance",
    icon: TestTube,
    categories: ["Testing"],
    color: "from-teal-500 to-cyan-400",
  },
  {
    id: "devops",
    title: "DevOps & Tools",
    description: "Deployment & Collaboration",
    icon: Wrench,
    categories: ["DevOps & Tools"],
    color: "from-slate-500 to-gray-400",
  },
  {
    id: "ai",
    title: "AI & ML",
    description: "Artificial Intelligence",
    icon: Brain,
    categories: ["AI & ML"],
    color: "from-violet-500 to-purple-400",
  },
  {
    id: "soft-skills", // لایه جدید
    title: "Soft Skills",
    description: "Personal Growth & Communication",
    icon: User,
    categories: ["Learning & Growth", "Work Style", "Languages"],
    color: "from-slate-500 to-gray-400",
  },
];

const techStack = [
  {
    category: "Frontend Core",
    items: [
      "HTML",
      "JavaScript",
      "TypeScript",
      "Vite",
      "React.js",
      "React Router",
      "Next.js",
      "SolidJS",
      "Svelte / SvelteKit",
      "Astro",
      "Tanstack",
    ],
    level: "Expert",
    type: "programming",
  },
  {
    category: "Styling & UI",
    items: ["CSS", "Responsive Design", "SASS/SCSS", "Tailwind CSS", "Shadcn"],
    level: "Expert",
    type: "programming",
  },
  {
    category: "State & Data",
    items: [
      "Context API",
      "Axios",
      "Zustand",
      "Zod",
      "React Hook Form",
      "TanStack Query (React Query)",
    ],
    level: "Advanced",
    type: "programming",
  },
  {
    category: "Backend",
    items: ["Node.js", "Express.js", "Bun"],
    level: "Expert",
    type: "programming",
  },
  {
    category: "Database",
    items: ["SQL Server", "MongoDB", "PostgreSQL"],
    level: "Advanced",
    type: "programming",
  },
  {
    category: "Mobile & Desktop",
    items: ["React Native", "PWA", "Electron.js"],
    level: "Advanced",
    type: "programming",
  },
  {
    category: "Testing",
    items: ["Jest", "React Testing Library"],
    level: "Intermediate",
    type: "programming",
  },
  {
    category: "DevOps & Tools",
    items: ["Git & GitHub", "Git Flow", "Docker", "Postman"],
    level: "Intermediate",
    type: "programming",
  },
  {
    category: "AI & ML",
    items: ["Prompt Engineering", "OpenAI API", "LangChain"],
    level: "Advanced",
    type: "programming",
  },
  {
    category: "Learning & Growth",
    items: ["Reading Tech Books", "Online Courses", "Tech Conferences"],
    level: "Passionate",
    type: "personalize",
  },
  {
    category: "Work Style",
    items: ["Remote-First", "Clean Code", "TDD"],
    level: "Preferred",
    type: "personalize",
  },
  {
    category: "Languages",
    items: ["Persian (Native)", "English (Intermediate)", "Russian (Beginner)"],
    level: "Communication",
    type: "personalize",
  },
];

const photosLinks = [
  {
    id: 1,
    icon: "/icons/gicon1.svg",
    title: "Library",
  },
  {
    id: 2,
    icon: "/icons/gicon2.svg",
    title: "Memories",
  },
];

const gallery = [
  {
    id: 1,
    img: "/images/gallery/1.gif",
  },
  {
    id: 2,
    img: "/images/gallery/1.gif",
  },
  {
    id: 3,
    img: "/images/gallery/1.gif",
  },
];

const socialItems = [
  {
    id: 1,
    icon: Mail,
    label: "Email",
    description: "mr.redmasterr@gmail.com",
    link: "mailto:mr.redmasterr@gmail.com",
    color: "hover:border-blue-500/50",
    action: () => console.log("Email"),
  },
  {
    id: 2,
    icon: Phone,
    label: "Phone",
    description: "09051811903",
    link: "tel:+989051811903",
    color: "hover:border-green-500/50",
    action: () => console.log("Phone"),
  },
  {
    id: 3,
    icon: Link,
    label: "LinkedIn",
    description: "linkedin.com/in/ali-shahbaz-a3aa29413",
    link: "linkedin.com/in/ali-shahbaz-a3aa29413",
    color: "hover:border-blue-400/50",
    action: () => console.log("LinkedIn"),
  },
  {
    id: 4,
    icon: Share2,
    label: "Instagram",
    description: "@ali.shahbaz.dev",
    link: "https://instagram.com/ali.shahbaz.dev",
    color: "hover:border-pink-500/50",
    action: () => console.log("Instagram"),
  },
  {
    id: 5,
    icon: Send,
    label: "Telegram",
    description: "https://t.me/aliish0_0",
    link: "https://t.me/aliish0_0",
    color: "hover:border-blue-300/50",
    action: () => console.log("Telegram"),
  },
  {
    id: 6,
    icon: Globe,
    label: "Website",
    description: "alishahbaz.dev",
    link: "https://alishahbaz.dev",
    color: "hover:border-purple-500/50",
    action: () => console.log("Website"),
  },
];
const courses = [
  {
    id: 1,
    title: "React Router V7 Masterclass",
    instructor: "Ali Shahbaz",
    platform: "Toplearn",
    difficulty: "Advanced",
    duration: "19.6h",
    image:
      "https://toplearn.com/img/course/%D9%85%D8%B3%D8%AA%D8%B1%DA%A9%D9%84%D8%A7%D8%B3_react_router_v7.jpg",
    link: "https://toplearn.com/courses/web-design/%D9%85%D8%B3%D8%AA%D8%B1-%DA%A9%D9%84%D8%A7%D8%B3-react-router-v7",
    completed: true,
    date: "Jan 2025",
  },
  {
    id: 2,
    title: "ChatGPT Pro Training",
    instructor: "Ali Shahbaz",
    platform: "Toplearn",
    difficulty: "Advanced",
    duration: "11h",
    image:
      "https://toplearn.com/img/course/%D8%A2%D9%85%D9%88%D8%B2%D8%B4_chatgpt_pro3.jpg",
    link: "https://toplearn.com/courses/windows/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-chatgp-pro",
    completed: true,
    date: "Oct 2024",
  },
  {
    id: 3,
    title: "Based PostCSS Training",
    instructor: "Ali Shahbaz",
    platform: "Toplearn",
    difficulty: "Beginner",
    duration: "33h",
    image: "https://faradars.org/wp-content/uploads/2025/12/13/fvwb345.svg",
    link: "https://faradars.org/courses/postcss-project-setup-plugins-fvwb345",
    completed: true,
    date: "Jul 2026",
  },
];
const navigationTabs = [
  { id: "all", label: "All", icon: Layers },
  { id: "programming", label: "Tech", icon: Code2 },
  { id: "personalize", label: "Personal", icon: User },
];
// ==================
const aiResponses = [
  {
    icon: Code,
    text: "React Projects",
    desc: "12 interactive components",
    tag: "Frontend",
    category: "projects",
  },
  {
    icon: Zap,
    text: "Backend APIs",
    desc: "8 RESTful services",
    tag: "Backend",
    category: "projects",
  },
  {
    icon: User,
    text: "Work Experience",
    desc: "5 years in tech",
    tag: "Career",
    category: "experience",
  },
  {
    icon: Terminal,
    text: "DevOps Pipeline",
    desc: "CI/CD automation",
    tag: "DevOps",
    category: "skills",
  },
];

const suggestedQuestions = [
  {
    text: "What are your top React projects?",
    icon: FolderOpen,
    color: "text-emerald-300",
  },
  {
    text: "Tell me about your work experience",
    icon: User,
    color: "text-blue-300",
  },
  {
    text: "Show me your backend skills",
    icon: Terminal,
    color: "text-purple-300",
  },
  {
    text: "What technologies do you use?",
    icon: Code,
    color: "text-amber-300",
  },
];

const categories = [
  { key: "projects", label: "Projects", icon: FolderOpen },
  { key: "experience", label: "Experience", icon: User },
  { key: "skills", label: "Skills", icon: Zap },
];
// ==============
const iconMap = {
  "React.js": FaReact,
  "Next.js": SiNextdotjs,
  Astro: SiAstro,
  HTML: FaHtml5,
  Vite: TbBrandVite,
  Tanstack: LuTreePalm,
  TypeScript: SiTypescript,
  JavaScript: IoLogoJavascript,
  SolidJS: FaReact,
  Shadcn: SiShadcnui,
  Axios: SiAxios,
  PWA: SiPwa,
  "Prompt Engineering": VscRobot,
  "Svelte / SvelteKit": FaReact,
  "Tailwind CSS": SiTailwindcss,
  CSS: FaCss3Alt,
  "SASS/SCSS": SiSass,
  "Responsive Design": FaLaptopCode,
  Zustand: BsFillGearFill,
  "Context API": FaReact,
  "TanStack Query (React Query)": BsFillGearFill,
  "React Hook Form": BsFillGearFill,
  Zod: BsFillGearFill,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  NestJS: SiNestjs,
  "React Router": SiReactrouter,
  Hono: FaServer,
  Bun: BsFillGearFill,
  JWT: BsFillGearFill,
  MongoDB: DiMongodb,
  PostgreSQL: SiPostgresql,
  "SQL Server": FaDatabase,
  Redis: SiRedis,
  "React Native": TbBrandReactNative,
  Expo: SiExpo,
  Flutter: SiFlutter,
  "Electron.js": SiElectron,
  Jest: SiJest,
  "React Testing Library": BsFillGearFill,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  AWS: FaAws,
  "Git & GitHub": SiGithub,
  "Git Flow": SiGit,
  Postman: SiPostman,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  "OpenAI API": SiOpenai,
  LangChain: BsFillGearFill,
  "RESTful API Development": FaRocket,
  "TanStack PWAs": FaRocket,
  "Reading Tech Books": FaUserGraduate,
  "Online Courses": FaLaptopCode,
  "Tech Conferences": FaGlobe,
  "Remote-First": FaLaptopCode,
  "Agile/Scrum": FaCode,
  "Clean Code": FaCode,
  TDD: FaCode,
  "Persian (Native)": FaLanguage,
  "English (Fluent)": FaLanguage,
  "German (Basic)": FaLanguage,
};

const iconColorMap = {
  "React.js": "text-blue-400",
  HTML: "text-red-500",
  "Next.js": "text-black",
  Vite: "text-purple-500",
  Axios: "text-gray-700",
  "React Router": "text-red-600",
  Shadcn: "text-black",
  "Prompt Engineering": "text-yellow-500",
  TypeScript: "text-blue-600",
  JavaScript: "text-yellow-400",
  Tanstack: "text-green-500",
  SolidJS: "text-blue-500",
  Astro: "text-orange-500",
  PWA: "text-blue-500",
  "Svelte / SvelteKit": "text-orange-500",
  "Tailwind CSS": "text-teal-400",
  CSS: "text-blue-500",
  "SASS/SCSS": "text-pink-500",
  "Responsive Design": "text-purple-500",
  Zustand: "text-amber-500",
  "Context API": "text-blue-400",
  "TanStack Query (React Query)": "text-red-500",
  "React Hook Form": "text-pink-500",
  Zod: "text-blue-500",
  "Node.js": "text-green-500",
  "Express.js": "text-gray-600",
  NestJS: "text-red-600",
  Hono: "text-orange-500",
  Bun: "text-amber-500",
  JWT: "text-purple-500",
  MongoDB: "text-green-600",
  PostgreSQL: "text-blue-400",
  "SQL Server": "text-blue-600",
  Redis: "text-red-500",
  "React Native": "text-blue-500",
  Expo: "text-gray-700",
  Flutter: "text-sky-500",
  "Electron.js": "text-purple-500",
  Jest: "text-red-500",
  "React Testing Library": "text-red-500",
  Docker: "text-blue-500",
  Kubernetes: "text-blue-600",
  AWS: "text-orange-400",
  "Git & GitHub": "text-gray-700",
  "Git Flow": "text-orange-600",
  Postman: "text-orange-500",
  TensorFlow: "text-orange-500",
  PyTorch: "text-red-500",
  "OpenAI API": "text-green-500",
  LangChain: "text-blue-500",
  "RESTful API Development": "text-green-500",
  "TanStack PWAs": "text-purple-500",
  "Reading Tech Books": "text-blue-500",
  "Online Courses": "text-green-500",
  "Tech Conferences": "text-purple-500",
  "Remote-First": "text-blue-500",
  "Agile/Scrum": "text-amber-500",
  "Clean Code": "text-green-500",
  TDD: "text-red-500",
  "Persian (Native)": "text-green-500",
  "English (Fluent)": "text-blue-500",
  "German (Basic)": "text-amber-500",
};

export {
  navLinks,
  dockApps,
  layers,
  techStack,
  photosLinks,
  gallery,
  socialItems,
  courses,
  categories,
  suggestedQuestions,
  aiResponses,
  navigationTabs,
  iconColorMap,
  iconMap,
};

const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    // ▶ Project 1
    {
      id: 1,
      name: "Portfolio App",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-10 left-5", // icon position inside Finder
      windowPosition: "top-[20vh] left-10", // optional: Finder window position
      children: [
        {
          id: 1,
          name: "Portfolio Project.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Resume Craft is more than an online resume — it's a digital business card with a powerful visual identity.",
            "Much like Nike's website transcends a simple storefront, this project goes far beyond a static introduction page.",
            "From the moment you land, it feels like stepping into a professional gallery of your capabilities — where every scroll, click, and animation tells a compelling story about your experience, skills, and creativity.",
            "What Sets This Resume Apart?",
            "Immersive Experience: GSAP and React work together to deliver cinematic, fluid animations that capture attention just like a luxury brand.",
            "Industry-Standard Speed & Responsiveness: Built with Next.js and TailwindCSS 4, it guarantees optimal performance, instant loading, and a flawless responsive experience across all devices.",
            "Intelligent State Management: With Zustand and Immer, data like project details, skills, and contact info are managed cleanly — with zero unnecessary re-renders.",
            "Advanced Interactive Features: Direct PDF viewing via react-pdf, interactive guidance with react-tooltip, modern consistent icons from lucide-react, and dynamic date formatting using dayjs.",
            "Polished Look & Feel: A high-contrast dark/light theme, clean readable typography, intelligent conditional styling with clsx, and scroll-triggered animations that reveal each section at the perfect moment — like a luxury storefront window.",
          ],
        },

        {
          id: 2,
          name: "AliShahbaz.com",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "...",
          position: "top-10 right-20",
        },
        {
          id: 3,
          name: "portfolio.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-42 left-10",
          imageUrl: "/images/portfolio/1.png",
        },
        {
          id: 4,
          name: "Portfolio package.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-40 left-80",
          description: [
            "@gsap/react + gsap — Professional-grade animation engine for cinematic scroll and transition effects that bring your story to life.",
            "@tailwindcss/vite — Ultra-fast styling with Vite integration for instant HMR and build performance.",
            "zustand — Lightweight, scalable state management with minimal boilerplate for handling app-wide data.",
            "immer — Simplifies immutable state updates with a mutable syntax, making state changes clean and predictable.",
            "lucide-react — Modern, consistent icon set for clean visual communication and better UX.",
            "react-tooltip — Elegant tooltips for guided user interaction and contextual help.",
            "react-pdf — Direct PDF resume rendering without leaving the page — seamless and professional.",
            "dayjs — Lightweight date formatting for project timelines and experiences with minimal footprint.",
            "tailwindcss — Utility-first CSS framework for rapid, responsive design with complete customization.",
            "clsx — Conditional className management for cleaner, more readable components and dynamic styling.",
            "react + react-dom — Latest React with concurrent features and efficient rendering for peak performance.",
          ],
        },
      ],
    },
  ],
};

const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About me",
  icon: "/icons/info.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "me.png",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-10 left-10",
      imageUrl: "/images/me/1.png",
    },
    {
      id: 2,
      name: "about-me.txt",
      icon: "/images/txt.png",
      kind: "file",
      fileType: "txt",
      position: "top-10 left-50",
      subtitle: "Meet the Developer Behind the Code",
      image: "/images/me/1.png",
      description: [
        "Hey! I’m Ali Shahbaz 👋",
        "Full-Stack JavaScript Developer specializing in React.js, Next.js, and Node.js with experience building scalable and high-performance web applications. Skilled in designing clean, maintainable front-end architectures and developing robust backend systems using modern JavaScript ecosystems. Focused on writing reusable components, optimizing performance, and delivering seamless user experiences. Experienced in translating complex requirements into production-ready applications through both educational and real-world projects. Passionate about modern web technologies, API-driven development, and building efficient, scalable software solutions.",
      ],
    },
  ],
};

const RESUME_LOCATION = {
  id: 3,
  type: "resume",
  name: "Resume",
  icon: "/icons/file.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "Resume.pdf",
      icon: "/images/pdf.png",
      kind: "file",
      fileType: "pdf",
    },
  ],
};

const TRASH_LOCATION = {
  id: 1,
  type: "trash",
  name: "Trash",
  icon: "/icons/trash.svg",
  kind: "image",
  children: [
    {
      id: 1,
      name: "trash1.gif",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-10 left-10",
      imageUrl: "/images/gallery/1.gif",
    },
  ],
};

export const locations = {
  work: WORK_LOCATION,
  about: ABOUT_LOCATION,
  resume: RESUME_LOCATION,
  trash: TRASH_LOCATION,
};

const INITIAL_Z_INDEX = 1000;

const WINDOW_CONFIG = {
  finder: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  contact: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  resume: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  safari: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  photos: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  terminal: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  txtfile: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  imgfile: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  archive: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
};

export { INITIAL_Z_INDEX, WINDOW_CONFIG };
